mongodb:
  image: 'mongo:3.2'
  restart: always
  command: --nojournal
  ports:
   - "27016:27017"
  volumes:
   - "./db/mongo/:/data/db"
orion:
  image: fiware/orion
  restart: always
  links:
    - mongodb
  ports:
    - "1026:1026"
  command: -dbhost mongodb
