mongodb:
  image: 'mongo:2.6'
  restart: always
  volumes:
   - "./db/mongo/:/data/db"
orion:
  image: fiware/orion
  restart: always
  links:
    - mongodb
  ports:
    - "1026:1026"
  command: -dbhost mongodb
