mongo:
  image: 'bitnami/mongodb'
  restart: always
  volumes:
   - "./db/mongo/:/bitnami/db"
orion:
  image: fiware/orion
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo -corsOrigin __ALL
