mongo:
  image: mongo:3.2
  volumes:
  - "./db/mongo/:/data/db"
  command: --nojournal
orion:
  image: fiware/orion
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo -corsOrigin __ALL
